global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # API Atendechat
  - job_name: 'atendechat-api'
    static_configs:
      - targets: ['localhost:9464']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
    # Labels para organização
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(?::\d+)?'
        replacement: '${1}'
      - source_labels: [__address__]
        target_label: service
        replacement: 'atendechat-api'
      - source_labels: [__address__]
        target_label: environment
        replacement: 'development'

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'redis'
      - source_labels: [__address__]
        target_label: environment
        replacement: 'development'

  # PostgreSQL (se expuser métricas)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['localhost:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'postgresql'
      - source_labels: [__address__]
        target_label: environment
        replacement: 'development'

  # Node Exporter (métricas do sistema)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'node-exporter'
      - source_labels: [__address__]
        target_label: environment
        replacement: 'development'

  # k6 (testes de carga)
  - job_name: 'k6'
    static_configs:
      - targets: ['localhost:6565']
    metrics_path: '/metrics'
    scrape_interval: 10s
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: service
        replacement: 'k6'
      - source_labels: [__address__]
        target_label: environment
        replacement: 'development'

# Configurações de armazenamento
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 15d
    retention.size: 50GB

# Configurações de alertas
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093

# Configurações de regras
rule_files:
  - "rules/slos.yml"
  - "rules/alerts.yml"
