# ========================================
# ATENDECHAT 2.0 - ALERTMANAGER CONFIG
# ========================================

global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alertmanager@seudominio.com'
  smtp_auth_username: 'seu-email@gmail.com'
  smtp_auth_password: 'sua-senha-app'

# ========================================
# TEMPLATES
# ========================================
templates:
  - '/etc/alertmanager/template/*.tmpl'

# ========================================
# ROUTE
# ========================================
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'web.hook'
  routes:
    # ========================================
    # ALERTAS CRÍTICAS (API DOWN)
    # ========================================
    - match:
        severity: critical
      receiver: 'critical-alerts'
      continue: true
      
    # ========================================
    # ALERTAS DE PERFORMANCE
    # ========================================
    - match:
        alertname: HighResponseTime
      receiver: 'performance-alerts'
      continue: true
      
    # ========================================
    # ALERTAS DE BANCO
    # ========================================
    - match:
        alertname: DatabaseConnectionError
      receiver: 'database-alerts'
      continue: true
      
    # ========================================
    # ALERTAS DE REDIS
    # ========================================
    - match:
        alertname: RedisConnectionError
      receiver: 'redis-alerts'
      continue: true

# ========================================
# RECEIVERS
# ========================================
receivers:
  # ========================================
  # WEBHOOK (Slack/Discord)
  # ========================================
  - name: 'web.hook'
    webhook_configs:
      - url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        send_resolved: true
        
  # ========================================
  # EMAIL CRÍTICO
  # ========================================
  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@seudominio.com'
        send_resolved: true
        headers:
          subject: '🚨 ALERTA CRÍTICO: {{ .GroupLabels.alertname }}'
          
  # ========================================
  # EMAIL PERFORMANCE
  # ========================================
  - name: 'performance-alerts'
    email_configs:
      - to: 'dev@seudominio.com'
        send_resolved: true
        headers:
          subject: '⚠️ ALERTA PERFORMANCE: {{ .GroupLabels.alertname }}'
          
  # ========================================
  # EMAIL BANCO
  # ========================================
  - name: 'database-alerts'
    email_configs:
      - to: 'dba@seudominio.com'
        send_resolved: true
        headers:
          subject: '🔴 ALERTA BANCO: {{ .GroupLabels.alertname }}'
          
  # ========================================
  # EMAIL REDIS
  # ========================================
  - name: 'redis-alerts'
    email_configs:
      - to: 'devops@seudominio.com'
        send_resolved: true
        headers:
          subject: '🟡 ALERTA REDIS: {{ .GroupLabels.alertname }}'

# ========================================
# INHIBIT RULES
# ========================================
inhibit_rules:
  # ========================================
  # SUPRIMIR ALERTAS MENORES QUANDO API ESTÁ DOWN
  # ========================================
  - source_match:
      severity: 'critical'
      alertname: 'APIDown'
    target_match:
      severity: 'warning'
    equal: ['service']
      
  # ========================================
  # SUPRIMIR ALERTAS DE PERFORMANCE QUANDO SERVIÇO ESTÁ DOWN
  # ========================================
  - source_match:
      alertname: 'ServiceDown'
    target_match:
      alertname: 'HighResponseTime'
    equal: ['service']

# ========================================
# TIME INTERVALS
# ========================================
time_intervals:
  - name: workdays
    time_intervals:
      - weekdays: ['monday:friday']
        times:
          - start_time: 09:00
            end_time: 18:00
            
  - name: weekends
    time_intervals:
      - weekdays: ['saturday', 'sunday']
        
  - name: nights
    time_intervals:
      - times:
          - start_time: 22:00
            end_time: 06:00
